### ISSUE TITLE
The progress circle is getting cut-off/clipped. It's never a smooth circle for me.

### ISSUE THREAD

**Issue by epiphany27** [JorgeCastilloPrz/FABProgressCircle#44]
![fab-ss1](https://user-images.githubusercontent.com/1677170/29029068-07790a3a-7ba4-11e7-887c-7c4bf39cb0cd.png)
![fab-ss2](https://user-images.githubusercontent.com/1677170/29029075-0bcde240-7ba4-11e7-9af7-046d372c9c0d.png)

Please let me know what am I doing wrong. I am trying below sample example. I do not have coordinator layout in my case, which I think should not be an issue. 

```
<com.github.jorgecastilloprz.FABProgressCircle
            android:id="@+id/fabProgressCircle"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@id/address_autocomplete_text_inp_layout"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="40dp"
            app:arcWidth="7dp">

            <!-- You can change it with the fab from the library you want to use -->
            <android.support.design.widget.FloatingActionButton
                android:id="@+id/fab"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_arrow_forward_white_24dp"
                app:borderWidth="0dp"/>

        </com.github.jorgecastilloprz.FABProgressCircle>
```

**Comment by crearo** [comment]
Use `android:clipToPadding="false"`. That should solve it for you.

**Comment by afedorychak** [comment]
This is indeed a bug in the library, it sets dimensions for the arc view based on hard coded expected fab size + single arc width. It should be using double arc width instead. Setting `clipToPadding` to false will help but only if you actually give `FABProgressCircle` some padding, otherwise it will still be clipped by `FABProgressCircle`'s parent.

**Comment by hablema** [comment]
Had the same issue. `android:clipToPadding="false"`  didn't solve it for me. Setting `app:useCompatPadding="true"` for the FloatingActionButton solved it for me.

**Comment by LucasBourgeois** [comment]
set a value to the layout-width and layout-height of the <com.github.jorgecastilloprz.FABProgressCircle /> tag
Then you can increase the arc-width to make it more visible.
like : 

`   android:layout_width="75dp"
    android:layout_height="75dp"
`
